### ISSUE TITLE
Does *stateen0[59] control mscontext if implemented?

### ISSUE THREAD

**Issue by YenHaoChen** [riscv/riscv-debug-spec#1008]
Hello, 

The *stateen0[59] controls scontext. When mstateen0[59]=0, accessing scontext from S/HS-mode raises an exception. Does the *stateen0[59] also control the mscontext, the alias of scontext, if implemented?

![image](https://github.com/riscv/riscv-debug-spec/assets/39526191/a3b0d43b-dffd-4c69-9294-26de665ad0ad)

**Comment by pdonahue-ventana** [comment]
mscontext is only for Debug 0.13.  mstateen0 is part of Smstateen.  The assumption probably was that nobody would implement both the old debug spec and the relatively new Smstateen extension.

Since the purpose of Smstateen is to prevent access to certain state rather than certain CSRs, I think that mstateen0[59] should control access to mscontext in this unusual implementation.

**Comment by YenHaoChen** [comment]
Thank you for the clarification.
