### ISSUE TITLE
Value of tinfo when selected trigger does not exist

### ISSUE THREAD

**Issue by jrahmeh** [riscv/riscv-debug-spec#1045]
In section 5.1 of the spec (version 1.0), item 5 says:  

> If info is 1, this trigger doesn’t exist. Exit the loop.

If the trigger does not exist, what should an implementation return tor the version field of tinfo?  Can an implementation implement item 5 as though it said:

>  if value of **tinfo** is 1, the trigger doesn't exist. Exit the loop.

**Comment by pdonahue-ventana** [comment]
I think that the implementation is required to have tinfo.version=1 even if tinfo.info=1 because the Sdtrig version is 1 even if tselect doesn't point to an implemented trigger.  While the version might not matter to the debugger in step 5 of this particular recipe (since the debugger is supposed to only look at the info field), the debugger isn't required to set tselect to an implemented trigger when trying to discover what version of Sdtrig is implemented.
