### ISSUE TITLE
What does postexec mean when there's no Program Buffer?

### ISSUE THREAD

**Issue by timsifive** [riscv/riscv-debug-spec#301]
Possibilities:
1. It's just a nop
2. The abstract command returns "not supported"

**Comment by mwachs5** [comment]
I guess another (gross) question/possibility Is similar to what happens if you have only 2 words of program buffer, and you write them both with say, nop, and you have no ebreak. Program buffer execution happens but once it runs off the end... it’s undefined, right? In the implementations I am aware of you’d get an exception once you run off the end. So maybe a legitimate possibility here is getting an exception as you try to execute the “null” program buffer

**Comment by timsifive** [comment]
How about saying that running a non-existant program buffer leads to undefined behavior, but we recommend it result in "not supported?"
