### ISSUE TITLE
What happens if setresethaltreq and clrresethaltreq are set simultaneously?

### ISSUE THREAD

**Issue by jhauser-us** [riscv/riscv-debug-spec#319]
If `dmcontrol` is written with bits `setresethaltreq` and `clrresethaltreq` both set (= 1), what happens?

**Comment by bdwyatt** [comment]
On a related note, was the intent for setresethaltreq and clrresethaltreq access to be W1 rather than W?

If not clrresethaltreq seems redundant, since you could accomplish the same thing by writing a 0 to setresethaltreq. Perhaps there's some other detail I'm missing, but reducing this down to a single field would also clear up the question about which takes priority.

**Comment by timsifive** [comment]
I've attempted to address all that in the #332. Please let me know if that doesn't make it clear.
