### ISSUE TITLE
itrigger mechanism change under CLIC proposal

### ISSUE THREAD

**Issue by chuanhua** [riscv/riscv-debug-spec#412]
There is a new CLIC proposal that will change the local interrupt mechanism as follows:
[CLIC proposal](https://github.com/sifive/clic-spec/blob/master/clic.adoc)

So the corresponding itrigger mechanism in the debug spec needs to be changed as well. Here is a proposal to change the itrigger mechanism in the following site:
[itrigger mechanism change proposal under CLIC.](https://github.com/sifive/clic-spec/issues/29)

Please see if this corresponding change makes sense or not.

Thanks.

Chuanhua, Andes Technology

**Comment by timsifive** [comment]
What's the status of the fast interrupt task group? If it looks like they have something that's likely to be ratified, it's probably time to see how we should accommodate it in the debug spec.

**Comment by Kevin-Andes** [comment]
Hi,

I am Kevin Chen and the co-chair of the Fast Interrupt task group. Yes, our CLIC proposal has been stable for quite some time and pretty much ready to be ratified. Also, Chuanhua's proposal looks quite straightforward and useful.

Thanks.

            Regards,
            Kevin

**Comment by timsifive** [comment]
Where can I see the latest working version of the fast interrupt document?

**Comment by Kevin-Andes** [comment]
Hi Tim,

Sorry for my slow reply. Please feel free to take a look at our fast interrupt proposal in the following github:

    https://github.com/riscv/riscv-fast-interrupt

Thanks.

    Regards,
    Kevin

**Comment by Kevin-Andes** [comment]
Hi Tim,

Just to clarify, are you suggesting to add thousands of registers (2 per interrupt) for infrequent cases that need triggering on more than 4 interrupts?  My first impression is that this sounds like a significant cost to pay for an uncommon use case...  Maybe we can try to think more and explore some cheaper alternatives.

Thanks.
Kevin

**Comment by timsifive** [comment]
More or less, although I think of it as adding one bit of state per interrupt that can be configured. I assume that a typical CLIC implementation will have maybe 16 possible interrupts, so it would add 16 bits of state in the CLIC, and 1 bit in the Debug Module.. @chuanhua's proposal would require 10 bits of state in the DM for that case, on RV32, and then you're limited to triggering on a max of 2 interrupt sources.

Are my numbers off?

**Comment by Kevin-Andes** [comment]
Let me clarify a little that CLIC is designed for small MCU or IoT processors (similar to Cortex-M class), so its users are very cost sensitive. This is why Krste keeps saying that adding 1-bit per interrupt is “very expensive” and he even tries to “reuse” 1-bit for different purposes in different modes.

Yes, your numbers are correct if there are only 16 interrupts. However, if there are more interrupts (as some of our members demand for 4096 interrupts), the cost will increase proportionally and become expensive…

To trigger on more interrupts as you suggested, I just thought of a simple idea that may help to initiate some brainstorming. If we add one or two mask fields, then we can trigger on consecutive groups of interrupts. For example, if we mask out and ignore the 2 least-significant-bits (LSBs), then we can trigger on a consecutive group of 2^2= 4 interrupts (e.g., interrupts 8, 9, 10, 11). Similarly, if we mask out the 5 LSBs, then we can trigger on a group of 2^5= 32 interrupts. One nice thing about this scheme is that it is has a fixed and very low cost. It would work the best if users can arrange their triggering interrupts in adjacent positions.

Do you think this may be useful?

**Comment by timsifive** [comment]
I didn't realize people were so cost-sensitive even when they have large number of interrupts.

Your idea for groups is interesting. How likely is it that people will be able to group interrupts the way that turns out to be useful for debugging? Or is this just run-time configuration that can be done by software?

Another option: Go with the one bit per interrupt scheme, but make implementing the bit optional for each interrupt. So a scheme with 16 interrupts could decide only the low 8 can be used for triggers. If the triggers are run-time configurable that's probably pretty good.

Another more philosophical question is where to implement this. So far we've been talking of putting all this in debug CSRs in the debug spec. Another option is to have the CLIC generate a single debug interrupt signal, which connects to each hart, where itrigger contains a single bit indicating whether to pay attention to the signal or not. Then the definition of exactly what set of interrupts can be selected to cause a debug interrupt can be in the CLIC spec and not in the Debug Spec. This is appealing to me because it means we don't need to make large changes to the Debug Spec when other extensions might want to be triggerable.

**Comment by Kevin-Andes** [comment]
You have brought up a very interesting question. I agree it is best not to cause too much change to the Debug Spec.  Perhaps both our groups need some time to discuss and try to find a most cost-effective and elegant solution.

**Comment by Kevin-Andes** [comment]
Hi Tim,

As you suggested, our group will implement the selection circuit inside our CLIC module to avoid making changes to the Debug Spec. Also, we have a couple questions and like to clarify with you:

1.  When does an interrupt trigger? Should we follow the behavior described in itrigger: "The trigger only fires if the hart takes a trap because of the interrupt."  Does it mean it only triggers when an interrupt is actually taken?  Or can we trigger when an interrupt is pending (and/or enabled)? Is the latter useful?

2.  When a trigger fires, should we follow the same behavior and assume "the requested action is taken just before the first instruction of the trap handler is executed."?

Thanks.
Kevin

**Comment by timsifive** [comment]
1. The line you quote is there specifically to ensure that the trigger only fires when the interrupt is actually taken, and not when the interrupt is masked, or not taken because we're already in an interrupt handler, etc. That ought to be a supported behavior. If you want to add an additional option to trigger even when the interrupt isn't masked, that seems fine.
2. Yes.

I'm struggling a little bit with the definition of actions. One option is for you to define the action field to associate with a "CLIC trigger," and in there say that the action field should be interpreted just as the action field in itrigger in the debug spec. The other option is for the CLIC just to generate one (or more) signals, that can separately be configured in itrigger, and so automatically gets the action behavior defined in the debug spec. I'm leaning towards the former, since it allows you more flexibility in exactly what triggering options you want to support.

**Comment by Kevin-Andes** [comment]
Thank you for the answers.

Regarding the "action," isn't it controlled globally by the Trigger Module? Are you suggesting CLIC can have different actions from the rest of triggers?  Are you also suggesting CLIC can have different actions for each individual interrupt? I thought it would be cheaper to share the same existing action control/setting in the Trigger Module...

**Comment by timsifive** [comment]
Actions should behave the same as they do for regular triggers, so I agree that using the same logic that takes actions should be reused.

The question is how the action is configured. Two options come to mind:
1. The action is configured in the CLIC, then the CLIC has an interface to the Trigger Module saying which action should be taken.
2. The action is configured in the Trigger Module (e.g. in itrigger), and the interface from CLIC to Trigger Module is simply a signal that indicates the action should be taken now.

The first interface gives you more options in configuring complicated triggers and actions. (E.g. enable trace when one interrupt source fires, and disable it when another one fires.) The second is probably a little bit cheaper to implement. My inclination is to go with the first one, enabling more powerful but expensive implementations, while specifying a simple base case that ends up costing almost the same as the second option. Whether having so many options is in the spirit of the CLIC spec I do not know.

**Comment by Kevin-Andes** [comment]
Thank you for your detailed explanation on each option. Nevertheless, we would probably prefer option 2 based on the principle we discussed in this week's group meeting (described in the next paragraph). The main reason is that we already have enough issues on our plate so we may not have the bandwidth to design more advanced triggering actions in the current stage. Also, so far we have not heard from our member companies demanding for advanced actions.

By the way, in our group meeting, we discussed whether we need additional triggering criteria ("If you want to add an additional option to trigger even when the interrupt isn't masked, that seems fine"). Krste's comment was that we should just do the same as the existing triggers and not create additional options. Therefore, we most likely won't design new advanced actions in the current stage.

**Comment by timsifive** [comment]
So for the debug spec, I think we'll want an additional bit in itrigger that enables the CLIC as a trigger source. Then when the CLIC sends the "fire a trigger" message, the action selected in itrigger is taken.

Does that sound good?

**Comment by Kevin-Andes** [comment]
Yes, that sounds good and simple.  Also, regarding the "fire a trigger" message, are you referring to one wire that looks like edge-triggered interrupt input?  Or do we need some kind of hand-shaking mechanism?

Thanks.

**Comment by timsifive** [comment]
In the debug spec we typically leave such things up to the implementation, because we focus on the software-observable behavior. How do you handle this for the CLIC delivering interrupts to the hart? Are they defined as a wire with an edge trigger, or as something less specific?

**Comment by Kevin-Andes** [comment]
Actually, CLIC is a local interrupt controller so it is integrated with the hart and does not deliver interrupts/signals to other harts. Nevertheless, CLIC can receive external interrupt inputs either as level- or edge-triggered signals. 

Does your module need to communicate with modules?

**Comment by timsifive** [comment]
The trigger module is tied to a single hart.

**Comment by Kevin-Andes** [comment]
That sounds great. If the trigger module is tied to a single hart just like CLIC, then there is no need for remote communication across distant harts. Since it is easy to send messages within a hart, we should not need to specify extra handshaking protocol.

**Comment by timsifive** [comment]
I think this was addressed in the CLIC spec. Is that right?

**Comment by Kevin-Andes** [comment]
Yes, this issue has been well discussed in our group. I will commit my draft proposal to the official spec and then send you a pointer for review shortly.

Thanks.

**Comment by timsifive** [comment]
Will this require any changes to the debug spec?

**Comment by Kevin-Andes** [comment]
Per your previous comment (attached again at the bottom), the debug spec should add one bit to select/enable CLIC as a trigger source. By the way, we may change the name "CLIC" before ratification because it is too similar to CLINT...

"So for the debug spec, I think we'll want an additional bit in itrigger that enables the CLIC as a trigger source. Then when the CLIC sends the "fire a trigger" message, the action selected in itrigger is taken."

**Comment by timsifive** [comment]
Since we had this discussion, we added tmexttrigger, for "trigger module external trigger input signals." That seems like a closer fit than adding a bit to itrigger, although it doesn't limit triggers depending on the current privilege mode.

@pdonahue-ventana, do you have an opinion on using tmexttrigger for a trigger from the CLIC?

**Comment by timsifive** [comment]
I made a PR that adds a bit to tmexttrigger, where I think it fits more naturally. Freeze is on Monday so I need to merge something then. Sorry for the late notice/attention.

**Comment by pdonahue-ventana** [comment]
> @pdonahue-ventana, do you have an opinion on using tmexttrigger for a trigger from the CLIC?

That seems like it would work.
