### ISSUE TITLE
Will try to resolve the known limitation that data value triggers (select =1) can only be supported for access sizes up to XLEN bits?

### ISSUE THREAD

**Issue by tsaiyenting** [riscv/riscv-debug-spec#623]
Hi,
In section 5.5.11, implementations such as RV32D or RV64V are able to perform loads and stores that are wider than XLEN. Because tdata2 is of size XLEN, MCONTROL might not be used to match full size data value.

Will RISC-V debug spec try to resolve this limitation?

**Comment by pdonahue-ventana** [comment]
See also:
- https://lists.riscv.org/g/tech-debug/topic/76550451#207 (specific to the V extension)
- https://lists.riscv.org/g/tech-debug/message/214 (which I think is more general and along the lines of what you're asking)

My understanding is that this deficiency will not be addressed in 1.0.0 since that spec has gone to stable status and any change in this area would be more than a clarification.  My opinion is that this should be addressed eventually, though.

**Comment by tsaiyenting** [comment]
Got it. Thanks for your reply.
