### ISSUE TITLE
What value should be written to xtval when triggers fire?

### ISSUE THREAD

**Issue by JamesKenneyImperas** [riscv/riscv-debug-spec#636]
Could you please clarify the values expected to be written to `xtval` registers when triggers fire and cause breakpoint exceptions? There is almost no information about this in either the Privileged or Debug specifications.

In the Privileged Specification, there is only one reference for each `xtval`, of this form:

> When a **hardware breakpoint is triggered**, or an address-misaligned, access-fault, or page-fault exception occurs on an instruction fetch, load, or store, **mtval is written with the faulting virtual address**.

The term _faulting virtual address_ is inapplicable here, because there is no fault, so this needs clarification. Some triggers (e.g. icount) have no associated address - is zero written in this case, or something else (e.g. the current PC)? Chained triggers can have multiple addresses (e.g. write to address A while executing at address B) - which if any address is written in such cases?

Ideally, the required behavior should be clearly stated for all trigger possibilities. If this is deemed to be implementation dependent, then that should be clearly stated, with possible implementations listed.

Thanks.

**Comment by pdonahue-ventana** [comment]
I agree that this should be cleaned up.

My assumption for the basic execute/load/store address triggers is that xtval should be written with the address just as if that address had a page fault or access fault.  On execute data triggers, it makes sense to treat them like illegal instruction exceptions and capture the instruction.  Load/store data triggers should probably similarly capture the load/store data.  Zero seems to make sense for icount, itrigger, etrigger, and tmexttrigger.

Chaining adds a whole new dimension.  There are lots of options including:
- always write zero
- the value that would have been written to mtval by the first trigger (as if it hadn't been chained)
- the value that would have been written by the last trigger (as if it hadn't been chained)
- the value that would have been written by the load/store trigger (if any) in the chain (since xepc already captures the PC).  But you can also chain load/store address and load/store data triggers so it would have to prioritize one over the other.
- the value that would have been written by the lowest priority trigger in the chain (from table 5.2).  This prioritizes load data over store data over load/store address over execute data over execute address.
- same as the previous item but invert the order to capture the highest priority trigger
- some combination.  For instance, it could allow the value from any trigger in the chain or zero (which is least constraining on implementations but least helpful to software).  Maybe there could be some recommendations along with the freedom.

These are all just my thoughts.  This should involve a wider discussion and the decision should be informed by what existing implementations do.
