### ISSUE TITLE
behavior of clearing icount.pending bit

### ISSUE THREAD

**Issue by larryrong** [riscv/riscv-debug-spec#677]
Hello

I have a question about clearing icount.pending bit. 
3 triggers are set as icount type as below
icount-1, m/s/u=0/0/1. icount.count=1.
icount-2, m/s/u=0/1/0. icount.count=1.
icount-3, m/s/u=0/1/1. icount.count=2.

The sequence flow is 
1. In U-mode, A trap is taken and mode is transfered to S-mode
=> icount-1.count=0, icount-1.pending=1
=> icount-3.count=1
2. In S-mode, A instruction is retried
=> icount-2.count=0. icount-2.pending=1
=> icount-3.count=0. icount-3.pending=1
=>Trigger fires

Do these 3 icount.pending bits clear at the same time? or clear icount.pending bits if the corresponding icount.s bit is set. (clear icount-2.pending and icount-3.pending)

Thanks,
Larry

**Comment by pdonahue-ventana** [comment]
Here's my interpretation.

The spec says:
> When pending is set, the trigger fires just before any further instructions are executed in a mode where the trigger is enabled.

After step 2 in your sequence, icount-2 and icount-3 both fire because it is going to execute the second instruction of the handler in S-mode and the triggers are enabled in S-mode.  But icount-1 does not fire because it is not enabled in S-mode.

And it says:
> As the trigger fires, pending is cleared.

This means that icount-2.pending and icount-3.pending are both cleared because they both fired.  Since icount-1 did not fire, icount-1.pending is not cleared.  It will fire and clear pending immediately after returning to U-mode.
