### ISSUE TITLE
WARL vs reset values

### ISSUE THREAD

**Issue by silabs-oysteink** [riscv/riscv-debug-spec#689]
If a CSR has a field set to WARL, and reset value specified as 0, what is the correct behavior?

Example:

A core will only support mcontrol6.action = 1. The spec specifies WARL, and a reset value of 0 for that bit.
It would not make sense to reset to 0 if the core will not support it, will the core still be compliant if it resets mcontrol6.action to 1? Or is the contents of a WARL CSR only considered valid after a write has been performed?

**Comment by pdonahue-ventana** [comment]
The privileged architecture v1.12 only requires the bare minimum to be reset.  It doesn't unconditionally require specific reset values on any WARL field.  It says that after reset "No WARL field contains an illegal value" (the RL part of WARL).  It says that MBE must be reset to 0 _if_ the value of 0 is supported (and if 0 is not supported then it must reset to the only legal value which is 1).  And it specifies reset values on a few non-WARL fields (something like 8 total bits across all CSRs plus 2 bits per PMP entry).  Of course, implementations can (and often do) reset more state if they want since everything else is UNSPECIFIED.

By contrast, debug specifies the reset values of almost everything even though, for example, in mcontrol6 the only real reset requirements (beyond the above "No WARL field contains an illegal value") could be either execute=store=load=0 or vs=vu=m=s=u=0 (and arguably only m=0 is necessary in order to prevent triggers from firing while the reset handler initializes things).  And scontext is required to be reset to 0 even though no trigger can match on scontext because after reset all triggers are disabled in all modes (and this is the reason it's OK that tdata2 isn't currently required to be reset).

I'm not sure how much thought was put into these reset values.  I don't think that most of them are necessary at all.
