### ISSUE TITLE
Default accessibility of mscontext

### ISSUE THREAD

**Issue by valtrix** [riscv/riscv-debug-spec#690]
Can you please clarify the accessibility restrictions for _mscontext_ CSR? Given it is encoded like a machine CSR, will an access from supervisor mode result in an illegal trap?

**Comment by timsifive** [comment]
Yes, that is right. This is why scontext was created. There really is no reason to implement mscontext unless you know you have some software that relies on it.

**Comment by JamesKenneyImperas** [comment]
@timsifive, the original `scontext` in this location was accessible in S mode, and the manual states that `mscontext` is an alias for `scontext` in its new location. These two things imply that `mscontext` should be accessible in S mode as well (otherwise it is not backwards-compatible, and not a strict alias). If `mscontext` is _not_ accessible in S mode, can the description of it be updated to clarify this?

Thanks.
