### ISSUE TITLE
Why do triggers in a chain have priority?

### ISSUE THREAD

**Issue by YenHaoChen** [riscv/riscv-debug-spec#747]
Hello,

The specification states that triggers in a chain have priority. However, It also says that only the final (last) trigger of the chain can be taken, and others are ignored.
The specification seems inconsistent to me. Can you help clarify this?

![image](https://user-images.githubusercontent.com/39526191/184779457-ca809a73-4f93-451f-9de1-5f66e1b1dd25.png)

![image](https://user-images.githubusercontent.com/39526191/184779511-b42aba36-ce79-4886-8b4b-e01793caac23.png)

Thank you
Best regards,
YenHaoChen

**Comment by pdonahue-ventana** [comment]
The action field on the last trigger is used.  The action fields on other triggers in the chain are ignored.  But all the other fields on the other triggers are not ignored.

Example: If you want to trigger only on a load to address X where the load has pc Y then you can chain two triggers.  The priority will be the load trigger priority (since that's lower than the PC trigger priority) and the action taken will be based on the action field of whichever trigger is last in the chain.

**Comment by YenHaoChen** [comment]
Thank you. Understood.
