### ISSUE TITLE
execution of ebreak and instruction retirement

### ISSUE THREAD

**Issue by eroom1966** [riscv/riscv-debug-spec#805]
Hi all
I have a question regarding ebreak.

In the privilege spec, for an ebreak instruction it says the following
> As ECALL and EBREAK cause synchronous exceptions, they are not considered to retire, and should not increment the minstret CSR.

In debug mode, when executing an ebreak instruction it says
> When ebreak is executed (indicating the end of the Program Buffer code) the hart returns to its park loop.

In which case this does not cause an exception, is this true ?
does this also mean that the minstret CSR would be incremented if counting enabled ?

Thx
Lee

**Comment by pdonahue-ventana** [comment]
I think that the priv spec's definitions of minstret and ebreak are authoritative.  It says that ebreak does not increment minstret because it causes an exception.  It doesn't say that ebreak doesn't increment minstret iff it causes an exception.  The rationale is somewhat non-normative.

Also, I don't really agree that ebreak doesn't cause an exception in the implementation described in the (non-normative) appendix.  It's an instruction that causes execution to go to some fixed vector which sounds a lot like a trap to me.  I could envision some other implementation that points the PC back to the start of the program buffer and just waits for further commands that ask it to begin execution (using a hardware state machine that executes only the PB contents instead of a park loop which has the state machine in software/ROM), but that's also exception-like.

So whether the rationale in the priv spec is non-normative or ebreak actually does cause an exception, my thinking is that it shouldn't increment minstret either way.
