### ISSUE TITLE
tmexttrigger clarification

### ISSUE THREAD

**Issue by tomaird** [riscv/riscv-debug-spec#980]
For `tmexttrigger`, is this interpretation of the spec correct:

- `select` is a WARL CSR field that software will write to indicate which external trigger input signal will cause this trigger to fire
- when the external trigger input indicates an external trigger firing, any `tmexttrigger`s that have the relevant `select` bit set, will internally fire and set the `hit` bit in these CSRs to indicate this trigger has fired (and take whatever `action` is set).

Or should it be:

- when the external trigger input indicates an external trigger firing, it sets the relevant `select` bit in any `tmexttrigger`s to indicate which external trigger input fired

I suspect it's the first one, but wanted clarification.

Additionally, assuming my first interpretation, for the description of `select` - "Selects any combination of up to 16 TM external trigger inputs that cause this trigger to fire." - does this mean that ALL of the selected external triggers must fire for this trigger to fire or that ANY of the selected external triggers can fire to cause this trigger to fire. This wording is ambiguous.

**Comment by pdonahue-ventana** [comment]
Yes, the first one.

The spec says "This trigger fires when *any selected* TM external trigger input signals."  "Any" means an arbitrary single external input trigger rather than all of them.  "Selected" means that there's a 1 in the select field, which is defined as the thing that selects the inputs that cause this trigger to fire.

If you want some sort of AND function where you need to have events A and B and C all happening before this trigger fires then you might need to have that AND logic in the unit that is the source of the external trigger input.  How those inputs are generated is beyond the scope of this spec.
